### ISSUE TITLE
docs: Sound play / stop response time

### ISSUE THREAD

**Issue by residentsparking** [alnitak/flutter_soloud#136] opened 2024-10-03 09:47 UTC
**Description**

I am struggling to achieve start / stop times below about 200-250ms. I have tried playing paused then unpausing / repausing. I have tried playing silence looped and mixing in my desired sound. I have tried reducing buffer size. I have checked sample rate. Both android.hardware.audio.low_latency and android.hardware.audio.pro are true on the device I am using for test. 

What am I missing? Thanks.

**Comment by alnitak** [comment] 2024-10-03 10:08
To better understand your issue, a minimal sample code could help.

If I understand correctly you load a sound e then, with maybe a play/pause button, you are noticing a delay?

**Comment by residentsparking** [comment] 2024-10-03 18:29
Thanks for replying quickly. Here's my main.dart in its latest incarnation where I am trying setVolume to modulate a steady sawtooth tone playing on loop on reaction to a FloatingActionButton. I am also changing the screen background; this is so I can video the two indications together and (mostly) eliminate button delay by comparing video frame numbers with the audio track. My best measurement (give or take half a video frame) is 216ms between the background changing and the sound beginning to come from the device speakers. 

[main.dart.txt](https://github.com/user-attachments/files/17248445/main.dart.txt)

**Comment by alnitak** [comment] 2024-10-06 09:24
I tried you sample. I didn't notice any lags on Android on a Samsung Galaxy Note S20.

I seen in your code that you are loading the sound and you are using "then" instead of assigning the Future result to an `AudioSource`. Maybe you are doing the same in your code. Loading a sound can take a while and maybe this is the cause of your problem. I suggest you to try loading the sound when the app starts, and then use the `SoLoud.play()`.

Also, reading your comments, I see you are managing video frames. Something I cannot test with your sample. I think the lag could come from something else you are doing in your app.

I close this issue, but if you have other and clearer information, please feel free to reopen.

**Closed by alnitak** 2024-10-06 09:24 UTC
Labels: documentation

**Comment by residentsparking** [comment] 2024-10-06 13:42
Thanks, that's given me some pointers.
